//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public int ID { get; set; }
        public int ParticipantID { get; set; }
        public int CommentsID { get; set; }
        public int ClassificationID { get; set; }
    
        public virtual Comments Comments { get; set; }
        public virtual Lookups Lookups { get; set; }
        public virtual participant participant { get; set; }
    }
}
