//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SATDEntities : DbContext
    {
        public SATDEntities()
            : base("name=SATDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Lookups> Lookups { get; set; }
        public virtual DbSet<participant> participant { get; set; }
    }
}
